-- MySQL Script generated by MySQL Workbench
-- Wed May 10 21:27:03 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vikingsBeer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vikingsBeer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vikingsBeer` DEFAULT CHARACTER SET utf8 ;
USE `vikingsBeer` ;

-- -----------------------------------------------------
-- Table `vikingsBeer`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vikingsBeer`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dt_nasc` DATE NULL,
  `name` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `password` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vikingsBeer`.`account` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `tel` VARCHAR(11) NULL,
  `Cpf` VARCHAR(11) NULL,
  `cep` VARCHAR(8) NULL,
  `end` VARCHAR(500) NULL,
  `num` INT NULL,
  `comp` VARCHAR(100) NULL,
  `cidade` VARCHAR(100) NULL,
  `foto_perfil` VARCHAR(100) NULL,
  PRIMARY KEY (`id`, `id_user`),
  INDEX `idUsuario_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `vikingsBeer`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`shopping_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vikingsBeer`.`shopping_cart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_account` INT NOT NULL,
  `status` INT NULL,
  `total_price` DECIMAL(10,2) NULL,
  `delivery` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `idUsuario_idx` (`id_account` ASC) VISIBLE,
  CONSTRAINT `id_account`
    FOREIGN KEY (`id_account`)
    REFERENCES `vikingsBeer`.`account` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`type_beer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vikingsBeer`.`type_beer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vikingsBeer`.`product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(1000) NULL,
  `price` DECIMAL(10,2) NULL,
  `image` VARCHAR(500) NULL,
  `id_type` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `Idtype_beer_idx` (`id_type` ASC) VISIBLE,
  CONSTRAINT `Id_type_beer`
    FOREIGN KEY (`id_type`)
    REFERENCES `vikingsBeer`.`type_beer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vikingsBeer`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vikingsBeer`.`order_item` (
  `id_cart` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quant` VARCHAR(45) NULL,
  INDEX `idProduct_idx` (`id_product` ASC) VISIBLE,
  INDEX `id_carrinho_idx` (`id_cart` ASC) VISIBLE,
  PRIMARY KEY (`id_cart`, `id_product`),
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `vikingsBeer`.`product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cart`
    FOREIGN KEY (`id_cart`)
    REFERENCES `vikingsBeer`.`shopping_cart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
